PemFile = "/Users/blaze/Desktop/AWS/AWSRnD.pem"
Regions = ["us-east-1","us-west-2","ap-south-1", "ap-northeast-2", "ap-southeast-1", "ap-southeast-2","ap-northeast-1","ca-central-1","eu-central-1","eu-west-1","eu-west-2"]
MasterTimeOut = 20
SSHUser = "ubuntu"
TargetSystem = "linux"
TargetArch = "amd64"
ConfTimeout = 10
CopyBinFiles = true
