Network = "udp"
Curve = "bn256"
Encoding = "gob"
MonitorPort = 10000
MaxTimeout = "2m"
Retrials = 1

[[Runs]]
    Nodes = 5
    Threshold = 3
    Failing = 2
    Processes = 2
    [Runs.Handel]
        Period = "20ms"
        UpdateCount = 1
        NodeCount = 10
        Timeout = "100ms"
