Network = "udp"
Curve = "bn256"
Encoding = "gob"
MonitorPort = 10000
MaxTimeout = "2m"
Retrials = 1

[[Runs]]
    Nodes = 64
    Threshold = 44
    Failing = 20
    Processes = 2
    [Runs.Handel]
        Period = "20ms"
        UpdateCount = 1
        NodeCount = 10
        Timeout = "100ms"
        UnsafeSleepTimeOnSigVerify = 0
