Network = "udp"
Curve = "bn256"
Encoding = "gob"
Allocator = "round"
MonitorPort = 10000
Debug = 0
Simulation = "handel"
MaxTimeout = "5m"
Retrials = 1
ResultFile = ""

[[Runs]]
  Nodes = 400
  Threshold = 300
  Failing = 0
  Processes = 100
  [Runs.Handel]
    Period = "20ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "100ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 800
  Threshold = 600
  Failing = 0
  Processes = 200
  [Runs.Handel]
    Period = "20ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "100ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 1200
  Threshold = 900
  Failing = 0
  Processes = 300
  [Runs.Handel]
    Period = "20ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "100ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 1600
  Threshold = 1200
  Failing = 0
  Processes = 400
  [Runs.Handel]
    Period = "20ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "100ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 2000
  Threshold = 1500
  Failing = 0
  Processes = 500
  [Runs.Handel]
    Period = "20ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "100ms"
    UnsafeSleepTimeOnSigVerify = 0
