Network = "udp"
Curve = "bn256"
Encoding = "gob"
Allocator = "round"
MonitorPort = 10000
Debug = 0
Simulation = "handel"
MaxTimeout = "5m"
Retrials = 1
ResultFile = ""

[[Runs]]
  Nodes = 2001
  Threshold = 1485
  Failing = 501
  Processes = 501
  [Runs.Handel]
    Period = "20ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 2001
  Threshold = 1485
  Failing = 501
  Processes = 501
  [Runs.Handel]
    Period = "20ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "100ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 2001
  Threshold = 1485
  Failing = 501
  Processes = 501
  [Runs.Handel]
    Period = "20ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "200ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 2001
  Threshold = 1010
  Failing = 981
  Processes = 501
  [Runs.Handel]
    Period = "20ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 2001
  Threshold = 1010
  Failing = 981
  Processes = 501
  [Runs.Handel]
    Period = "20ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "100ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 2001
  Threshold = 1010
  Failing = 981
  Processes = 501
  [Runs.Handel]
    Period = "20ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "200ms"
    UnsafeSleepTimeOnSigVerify = 0
