Network = "udp"
Curve = "bn256"
Encoding = "gob"
Allocator = "random"
MonitorPort = 10000
Debug = 0
Simulation = "handel"
MaxTimeout = "5m"
Retrials = 1
ResultFile = ""

[[Runs]]
  Nodes = 100
  Threshold = 75
  Failing = 25
  Processes = 50
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 300
  Threshold = 223
  Failing = 75
  Processes = 150
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 500
  Threshold = 372
  Failing = 125
  Processes = 250
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 1000
  Threshold = 743
  Failing = 250
  Processes = 500
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 1500
  Threshold = 1114
  Failing = 375
  Processes = 750
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 2000
  Threshold = 1485
  Failing = 500
  Processes = 1000
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
