Network = "udp"
Curve = "bn256"
Encoding = "gob"
Allocator = "random"
MonitorPort = 10000
Debug = 0
Simulation = "handel"
MaxTimeout = "5m"
Retrials = 1
ResultFile = ""

[[Runs]]
  Nodes = 2000
  Threshold = 1000
  Failing = 500
  Processes = 1000
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 3000
  Threshold = 1500
  Failing = 750
  Processes = 1500
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 4000
  Threshold = 2000
  Failing = 1000
  Processes = 2000
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
