Network = "udp"
Curve = "bn256"
Encoding = "gob"
Allocator = "random"
MonitorPort = 10000
Debug = 0
Simulation = "handel"
MaxTimeout = "5m"
Retrials = 1
ResultFile = ""

[[Runs]]
  Nodes = 100
  Threshold = 66
  Failing = 25
  Processes = 100
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 300
  Threshold = 198
  Failing = 75
  Processes = 300
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 500
  Threshold = 330
  Failing = 125
  Processes = 500
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 1000
  Threshold = 660
  Failing = 250
  Processes = 1000
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 1500
  Threshold = 990
  Failing = 375
  Processes = 1500
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 2000
  Threshold = 1320
  Failing = 500
  Processes = 2000
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 2500
  Threshold = 1650
  Failing = 625
  Processes = 2000
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 3000
  Threshold = 1980
  Failing = 750
  Processes = 2000
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 3500
  Threshold = 2310
  Failing = 875
  Processes = 2000
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 4000
  Threshold = 2640
  Failing = 1000
  Processes = 2000
  [Runs.Handel]
    Period = "50ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
