Network = "udp"
Curve = "bn256"
Encoding = "gob"
Allocator = "round"
MonitorPort = 10000
Debug = 0
Simulation = "handel"
MaxTimeout = "5m"
Retrials = 1
ResultFile = ""


[[Runs]]
  Nodes = 4000
  Threshold = 3960
  Failing = 40
  Processes = 2000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 4000
  Threshold = 3000
  Failing = 40
  Processes = 2000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 4000
  Threshold = 2040
  Failing = 40
  Processes = 2000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 4000
  Threshold = 3000
  Failing = 1000
  Processes = 2000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
[[Runs]]
  Nodes = 4000
  Threshold = 2040
  Failing = 1000
  Processes = 2000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0

[[Runs]]
  Nodes = 4000
  Threshold = 2040
  Failing = 1960
  Processes = 2000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 0
