Network = "udp"
Curve = "bn256"
Encoding = "gob"
Allocator = "round"
MonitorPort = 10000
Debug = 0
Simulation = "handel"
MaxTimeout = "5m"
Retrials = 1
ResultFile = ""

[[Runs]]
  Nodes = 100
  Threshold = 99
  Failing = 0
  Processes = 100
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 3

[[Runs]]
  Nodes = 300
  Threshold = 297
  Failing = 0
  Processes = 300
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 3

[[Runs]]
  Nodes = 500
  Threshold = 495
  Failing = 0
  Processes = 500
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 3

[[Runs]]
  Nodes = 1000
  Threshold = 990
  Failing = 0
  Processes = 1000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 3

[[Runs]]
  Nodes = 1500
  Threshold = 1485
  Failing = 0
  Processes = 1500
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 3

[[Runs]]
  Nodes = 2000
  Threshold = 1980
  Failing = 0
  Processes = 1000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 3

[[Runs]]
  Nodes = 2500
  Threshold = 2475
  Failing = 0
  Processes = 1250
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 3

[[Runs]]
  Nodes = 3000
  Threshold = 2970
  Failing = 0
  Processes = 1500
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 3

[[Runs]]
  Nodes = 4000
  Threshold = 3960
  Failing = 0
  Processes = 2000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 3

[[Runs]]
  Nodes = 5000
  Threshold = 4950
  Failing = 0
  Processes = 2500
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 3

[[Runs]]
  Nodes = 6000
  Threshold = 5940
  Failing = 0
  Processes = 3000
  [Runs.Handel]
    Period = "10ms"
    UpdateCount = 1
    NodeCount = 10
    Timeout = "50ms"
    UnsafeSleepTimeOnSigVerify = 3
